version: 2.1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:18-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Docker image
          command: docker build -t ozorku/node-cicd-demo:$CIRCLE_SHA1 .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: docker push ozorku/node-cicd-demo:$CIRCLE_SHA1